export const metadata = {
  title: "Scholarly",
  description: "Generated by create next app",
  openGraph: {
    title: "Scholarly",
    description: "Generated by create next app",
    images: [
      {
        url: "/images/scholarly-logo.png", 
        width: 1200,
        height: 630,
        alt: "Scholarly Logo",
      },
    ],
  },
};
